# NumPy : Practice Problems 1

In [75]:
import numpy as np

# 1. Create a null vector of size 10 but the fifth value which is 1.

In [16]:
vect1 = np.array([0,0,0,0,1,0,0,0,0,0])
print(vect1)
print(vect1.size)
print(vect1[4])

[0 0 0 0 1 0 0 0 0 0]
10
1


# 2. Create a vector with values ranging from 10 to 49.

In [21]:
vect2 = np.arange(10,50)
print(vect2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# 3. Create a 3x3 matrix with values ranging from 0 to 8

In [37]:
matrix1 = np.array([[0,1,2],
                   [3,4,5],
                   [6,7,8]])
print(matrix1)
print(matrix1.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [52]:
vect3 = np.array([1,2,0,0,4,0])
print(vect3[vect3 != 0])

[1 2 4]


# 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [50]:
np.random.seed(5)
matrix2 = np.random.randn(10,10)
print(matrix2.min())
print(matrix2.max())
print(matrix2.shape)

-2.859687966622556
2.43077118700778
(10, 10)


# 6. Create a random vector of size 30 and find the mean value.

In [74]:
np.random.seed(10)
vect4 = np.random.randn(30)
print(vect4,'\n')
print(vect4.size)
print(vect4.mean())

[ 1.3315865   0.71527897 -1.54540029 -0.00838385  0.62133597 -0.72008556
  0.26551159  0.10854853  0.00429143 -0.17460021  0.43302619  1.20303737
 -0.96506567  1.02827408  0.22863013  0.44513761 -1.13660221  0.13513688
  1.484537   -1.07980489 -1.97772828 -1.7433723   0.26607016  2.38496733
  1.12369125  1.67262221  0.09914922  1.39799638 -0.27124799  0.61320418] 

30
0.19799139176527716
